import time
import os
from kubernetes import client, config, watch
from groq import Groq
from github import Github
from dotenv import load_dotenv
# --- CONFIGURATION ---
load_dotenv()
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO_NAME = 'self-heal-cluster'
YAML_PATH = 'bomb.yml'  # Path to the file inside your repo

# Initialize Clients
ai_client = Groq(api_key=GROQ_API_KEY)
gh_client = Github(GITHUB_TOKEN)
config.load_kube_config() # Assumes you're running locally with access to your cluster
v1 = client.CoreV1Api()

def get_ai_fix(pod_name, image_name, error_reason):
    print(f"🤖 Brain: Analyzing misspelled image '{image_name}'...")
    
    prompt = f"""
    Context: A Kubernetes Pod '{pod_name}' is failing with error '{error_reason}'.
    The image defined is '{image_name}'.
    
    Task: 
    1. Identify the typo in the image name.
    2. Provide ONLY the corrected YAML for the Pod. 
    3. Keep the output as valid YAML only, no conversational text.
    """
    
    completion = ai_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}]
    )
    return completion.choices[0].message.content

def open_github_pr(corrected_yaml):
    print("🐙 Executor: Opening GitHub Pull Request...")
    repo = gh_client.get_repo(REPO_NAME)
    
    # Create a unique branch name
    branch_name = f"fix-image-typo-{int(time.time())}"
    main_branch = repo.get_branch("main")
    
    # 1. Create branch
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main_branch.commit.sha)
    
    # 2. Update File
    contents = repo.get_contents(YAML_PATH, ref="main")
    repo.update_file(
        path=YAML_PATH,
        message="AIOps: Fixed image name typo in manifest",
        content=corrected_yaml,
        sha=contents.sha,
        branch=branch_name
    )
    
    # 3. Create PR
    pr = repo.create_pull(
        title="[AIOps] Fix: Corrected misspelled container image",
        body="Automated fix generated by Groq AI after detecting ErrImagePull.",
        head=branch_name,
        base="main"
    )
    print(f"✅ PR Created: {pr.html_url}")

def monitor_cluster():
    print("👀 Watcher: Monitoring for Image Pull errors...")
    w = watch.Watch()
    # The loop starts here
    for event in w.stream(v1.list_pod_for_all_namespaces):
        pod = event['object']
        status = pod.status.container_statuses

        if status:
            for c in status:
                # The safety check must be inside the loop for each container 'c'
                state = c.state.waiting
                if state and hasattr(state, 'reason') and state.reason in ["ErrImagePull", "ImagePullBackOff"]:
                    print(f"\n[!] ALERT: Pod '{pod.metadata.name}' is failing to pull image!")

                    # Capture details
                    image_used = c.image
                    reason = state.reason

                    # Run the Loop
                    fix_yaml = get_ai_fix(pod.metadata.name, image_used, reason)
                    open_github_pr(fix_yaml)

                    print("Waiting 60s before next scan to avoid spam...")
                    time.sleep(60)

if __name__ == "__main__":
    monitor_cluster()
